CREATE TABLE students (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100)  DEFAULT NULL,
    nim VARCHAR(10) DEFAULT NULL UNIQUE,
    email VARCHAR(100) DEFAULT NULL UNIQUE,
    phone VARCHAR(12) DEFAULT NULL UNIQUE
);

CREATE TABLE ADMIN(
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(100) UNIQUE,
    password VARCHAR(100)
);

INSERT INTO ADMIN(username,password) VALUES ('sammidev','sammidev');

CREATE TABLE product(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) DEFAULT NULL,
    price DECIMAL DEFAULT NULL
);

INSERT INTO product(name,price) VALUES('mouse','1231.123');